prefect_agent:
  job:
    imagePullSecrets: ''
    imagePullPolicy: ''
    resources:
      requests:
        memory: ''
        cpu: ''
      limits:
        memory: ''
        cpu: ''
  prefectLabels: '[]'
  prefect:
    context:
      secrets:
        gcp_credentials: '{}'